In [ ]:
!pip install stable_baselines3[extra]

In [12]:
import os
import gymnasium as gym  # ✅ Use gymnasium instead of gym
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv  
from stable_baselines3.common.evaluation import evaluate_policy


In [14]:
environment_name = 'CartPole-v1'
env = gym.make(environment_name)

In [24]:
environment_name

'CartPole-v1'

In [56]:
env = gym.make("CartPole-v1", render_mode="human")
episodes=5
for episode in range(1,episodes+1):
    state = env.reset()
    done = False #varibles
    score = 0

    while not done:
        env.render()
        action=env.action_space.sample()
        n_state,reword,terminated, truncated,info = env.step(action)#mekedi me action ene enawa 4 veriales 
        done = terminated or truncated 
        score += reword
    print('Episode:{} Score:{}'.format(episode,score))


Episode:1 Score:11.0
Episode:2 Score:32.0
Episode:3 Score:32.0
Episode:4 Score:9.0
Episode:5 Score:19.0


In [58]:
env.close()
    

In [26]:
env.reset()
# me enne envirement eke values

(array([0.00819078, 0.02932892, 0.03381328, 0.01614216], dtype=float32), {})

In [30]:
# simply loop
episodes = 5
for episode in range(1,episodes+1):
    print(episode)

1
2
3
4
5


In [32]:
env.step(1)

(array([ 0.00877736,  0.22395004,  0.03413612, -0.26568344], dtype=float32),
 1.0,
 False,
 False,
 {})

In [40]:
env.action_space

Discrete(2)

In [36]:
env.action_space.sample()
# me envirment eke thiyenne action dekai 
# evagen random ekk thorala denawa

np.int64(0)

In [38]:
env.observation_space.sample()
# action ekata adala observation gennala denwa randoem

array([-3.62931   , -0.8275356 , -0.25950262, -2.3802783 ], dtype=float32)

In [62]:
# Make your Directories First
log_path = os.path.join('Training','Logs')

In [64]:
log_path

'Training\\Logs'

In [66]:
env = gym.make(environment_name,render_mode="human")
env = DummyVecEnv([lambda:env])#api hada gannawa dummy vector ekk
model = PPO('MlpPolicy',env,verbose=1,tensorboard_log=log_path)
# log_path Folder path where TensorBoard training logs will be saved (so you can visualize learning curves).

Using cpu device


In [68]:
PPO??

Init signature:
PPO(
    policy: Union[str, type[stable_baselines3.common.policies.ActorCriticPolicy]],
    env: Union[gymnasium.core.Env, ForwardRef('VecEnv'), str],
    learning_rate: Union[float, Callable[[float], float]] = 0.0003,
    n_steps: int = 2048,
    batch_size: int = 64,
    n_epochs: int = 10,
    gamma: float = 0.99,
    gae_lambda: float = 0.95,
    clip_range: Union[float, Callable[[float], float]] = 0.2,
    clip_range_vf: Union[NoneType, float, Callable[[float], float]] = None,
    normalize_advantage: bool = True,
    ent_coef: float = 0.0,
    vf_coef: float = 0.5,
    max_grad_norm: float = 0.5,
    use_sde: bool = False,
    sde_sample_freq: int = -1,
    rollout_buffer_class: Optional[type[stable_baselines3.common.buffers.RolloutBuffer]] = None,
    rollout_buffer_kwargs: Optional[dict[str, Any]] = None,
    target_kl: Optional[float] = None,
    stats_window_size: int = 100,
    tensorboard_log: Optional[str] = None,
    policy_kwargs: Optional[dict[str, Any]]

In [70]:
model.learn(total_timesteps=20000)

Logging to Training\Logs\PPO_1
-----------------------------
| time/              |      |
|    fps             | 42   |
|    iterations      | 1    |
|    time_elapsed    | 48   |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 43          |
|    iterations           | 2           |
|    time_elapsed         | 94          |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.008323753 |
|    clip_fraction        | 0.109       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.686      |
|    explained_variance   | 9.86e-05    |
|    learning_rate        | 0.0003      |
|    loss                 | 5.91        |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0166     |
|    value_loss           | 51.6        |
-----------------------------------------
---

In [16]:
PPO_Path = os.path.join('Training','Saved Models','PPO_Model_Cartpole')


In [74]:
model.save(PPO_Path)

C:\Users\hp\.codegeex\mamba\envs\codegeex-agent\Lib\site-packages\stable_baselines3\common\save_util.py:284: UserWarning: Path 'Training\Saved Models' does not exist. Will create it.
  warnings.warn(f"Path '{path.parent}' does not exist. Will create it.")


In [ ]:
del model #apita model eka delete karnna puluwan

In [18]:
PPO_Path

'Training\\Saved Models\\PPO_Model_Cartpole'

In [52]:
env = gym.make("CartPole-v1", render_mode="human")
model=PPO.load(PPO_Path, env=env)

Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


In [22]:
env.close()

In [54]:
model = PPO.load(PPO_Path,env=env)

Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


In [26]:
env = gym.make("CartPole-v1", render_mode="human")
evaluate_policy(model,env,n_eval_episodes=10,render=True)

C:\Users\hp\.codegeex\mamba\envs\codegeex-agent\Lib\site-packages\stable_baselines3\common\evaluation.py:70: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  warnings.warn(


(np.float64(485.1), np.float64(33.155542523083525))

In [30]:
env.close()

In [56]:
obs, info = env.reset()
action, _= model.predict(obs)
action

array(1)

In [58]:
env = gym.make("CartPole-v1", render_mode="human")
episodes=5
for episode in range(1,episodes+1):
    state = env.reset()
    done = False #varibles
    score = 0

    while not done:
        env.render()
        action, _= model.predict(obs)
        n_state,reword,terminated, truncated,info = env.step(action)#mekedi me action ene enawa 4 veriales 
        done = terminated or truncated 
        score += reword
    print('Episode:{} Score:{}'.format(episode,score))


Episode:1 Score:16.0
Episode:2 Score:11.0
Episode:3 Score:14.0
Episode:4 Score:24.0
Episode:5 Score:14.0


In [60]:
env.close()

In [62]:
obs = env.reset()

error: display Surface quit

In [64]:
obs

array([-0.00609767,  0.03774733, -0.04190294, -0.02562532], dtype=float32)

In [66]:
model.predict(obs)

(array(1), None)

In [68]:
env.action_space.sample()

np.int64(1)

In [74]:
action, _ = model.predict(obs)

In [76]:
env.action_space.sample()

np.int64(0)

In [80]:
import gymnasium as gym

env.close()  # just in case the old env is still active
env = gym.make("CartPole-v1", render_mode="human")  # recreate environment
obs, info = env.reset()

for _ in range(1000):
    action = env.action_space.sample()  # random action
    obs, reward, terminated, truncated, info = env.step(action)
    if terminated or truncated:
        obs, info = env.reset()

env.close()


In [82]:
env.step(action)

error: display Surface quit

In [86]:
log_path= r'C:\Users\hp\Desktop\work\ML\RL\Training\Logs'

In [88]:
training_log_path = os.path.join(log_path, 'PPO_1')

In [90]:
training_log_path

'C:\\Users\\hp\\Desktop\\work\\ML\\RL\\Training\\Logs\\PPO_1'

In [92]:
!tensorboard --logdir = {traning_log_path}

2025-10-24 17:27:39.664114: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-10-24 17:27:49.103308: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
usage: tensorboard [-h] [--helpfull] [--logdir PATH] [--logdir_spec PATH_SPEC]
                   [--host ADDR] [--bind_all] [--port PORT]
                   [--reuse_port BOOL] [--load_fast {false,auto,true}]
                   [--extra_data_server_flags EXTRA_DATA_SERVER_FLAGS]
                   [--grpc_creds_type {local,ssl,ssl_dev}]
                   [--grpc_data_provider PORT] [--purge_orphaned_data BO

In [94]:
from stable_baselines3.common.callbacks import EvalCallback,StopTrainingOnRewardThreshold

In [96]:
save_path=os.path.join('Traning','saved Models')

In [100]:
from stable_baselines3.common.callbacks import StopTrainingOnRewardThreshold, EvalCallback

# Define stop condition when average reward reaches 200
stop_callback = StopTrainingOnRewardThreshold(reward_threshold=200, verbose=1)

# Evaluation callback to monitor training performance
eval_callback = EvalCallback(
    env,
    callback_on_new_best=stop_callback,
    eval_freq=10000,
    best_model_save_path=save_path,
    verbose=1
)


In [102]:
model=PPO('MlpPolicy',env,verbose=1,tensorboard_log=log_path)

Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


In [110]:
model.learn(total_timesteps=20000, callback=eval_callback)

error: display Surface quit

In [106]:
env.close()

In [112]:
env = gym.make("CartPole-v1", render_mode="rgb_array")


In [114]:
model=PPO('MlpPolicy',env,verbose=1,tensorboard_log=log_path)

Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


In [116]:
model.learn(total_timesteps=20000, callback=eval_callback)

Logging to C:\Users\hp\Desktop\work\ML\RL\Training\Logs\PPO_2
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 23.4     |
|    ep_rew_mean     | 23.4     |
| time/              |          |
|    fps             | 460      |
|    iterations      | 1        |
|    time_elapsed    | 4        |
|    total_timesteps | 2048     |
---------------------------------
---------------------------------------
| rollout/                |           |
|    ep_len_mean          | 27.6      |
|    ep_rew_mean          | 27.6      |
| time/                   |           |
|    fps                  | 377       |
|    iterations           | 2         |
|    time_elapsed         | 10        |
|    total_timesteps      | 4096      |
| train/                  |           |
|    approx_kl            | 0.0083602 |
|    clip_fraction        | 0.113     |
|    clip_range           | 0.2       |
|    entropy_loss         | -0.686    |
|    explained_variance   | -2.98e-05 

C:\Users\hp\.codegeex\mamba\envs\codegeex-agent\Lib\site-packages\stable_baselines3\common\evaluation.py:70: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  warnings.warn(


error: display Surface quit

In [118]:
net_arch=[dict(pi=[128,128,128,128], vf=[128,128,128,128])]


In [126]:
model = PPO(
    policy='MlpPolicy',
    env=env,
    verbose=1,
    tensorboard_log=log_path,
    policy_kwargs={'net_arch': net_arch}
)

Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


In [124]:
model.learn(total_timesteps=20000, callback=eval_callback)

Logging to C:\Users\hp\Desktop\work\ML\RL\Training\Logs\PPO_4
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 306      |
|    ep_rew_mean     | 306      |
| time/              |          |
|    fps             | 495      |
|    iterations      | 1        |
|    time_elapsed    | 4        |
|    total_timesteps | 2048     |
---------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 339          |
|    ep_rew_mean          | 339          |
| time/                   |              |
|    fps                  | 341          |
|    iterations           | 2            |
|    time_elapsed         | 12           |
|    total_timesteps      | 4096         |
| train/                  |              |
|    approx_kl            | 0.0141159985 |
|    clip_fraction        | 0.123        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.547     

error: display Surface quit

In [129]:
import gymnasium as gym
env = gym.make("CartPole-v1", render_mode=None)  # Do NOT render during training
eval_env = gym.make("CartPole-v1", render_mode=None)


In [131]:
from stable_baselines3.common.callbacks import EvalCallback, StopTrainingOnRewardThreshold

stop_callback = StopTrainingOnRewardThreshold(reward_threshold=200, verbose=1)
eval_callback = EvalCallback(
    eval_env,
    callback_on_new_best=stop_callback,
    eval_freq=10000,
    best_model_save_path=save_path,
    verbose=1,
    render=False  # <--- Important!
)


In [133]:
model.learn(total_timesteps=20000, callback=eval_callback)

Logging to C:\Users\hp\Desktop\work\ML\RL\Training\Logs\PPO_5
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 24.5     |
|    ep_rew_mean     | 24.5     |
| time/              |          |
|    fps             | 457      |
|    iterations      | 1        |
|    time_elapsed    | 4        |
|    total_timesteps | 2048     |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 32          |
|    ep_rew_mean          | 32          |
| time/                   |             |
|    fps                  | 323         |
|    iterations           | 2           |
|    time_elapsed         | 12          |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.015084265 |
|    clip_fraction        | 0.224       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.681      |
|    expla

In [135]:
# Save the trained model
model.save("PPO_2")  # This saves the weights and policy
